### ISSUE TITLE
0 - Class '["GoogleFonts"]' not found

### ISSUE THREAD

**Issue by pklinke** [JoomTools/plg_system_jtaldef#7]
When plugin is activated, site throws error above 
1.0.13 and 1.0.14

When I place plugin as last loaded error is gone but fonts are still loaded from google.

Update 20.09.2022:
Again tested with plg_system_jtaldef-2.0.0-dev.zip:
Again 0 - Call to undefined method Jtaldef\Helper\JtaldefHelper::getNewFileContent() when "Prüfe <style> im <head>" is activated. Google Font is still loaded from Google.

**Comment by degobbis** [comment]
@pklinke is the issue resolved with the latest version?

**Comment by pklinke** [comment]
if plg_system_jtaldef-2.0.0-dev.zip is the latest, then yes

**Comment by degobbis** [comment]
Hmm... 
A while ago I had replied to this via email, but that doesn't seem to have arrived here.

I wrote:
Please go into the plugin configuration and select the `GogleFonts` service again.

Delete the index if something is displayed and save the settings. That should fix the problem.

This error occurred after a change in Joomla, where the default values from the manifest (XML) were stored differently in the database than after saving in the configuration.

**Comment by pklinke** [comment]
Still the same issues. I had removed and reinstalled and setup again.

**Comment by degobbis** [comment]
Good, I have now created a new version.
You can download from the releases: https://github.com/joomtools/plg_system_jtaldef/releases
  or You can configure your update server as in my description below.

Please test the following for me:

1. If the update goes through without any problems.

To do this, please change the minimum stability of the updates to "Release Candidate" in the overview of the updates, under options, then an update to 2.0.0-rc1 should be displayed. 

Don't forget to set it back to "Stable" after the update.

2. Completely uninstall and reinstall.


Besides some code restructuring, I think I also fixed the bug you are experiencing.

Thank you.

**Comment by pklinke** [comment]
0 - Call to undefined method Jtaldef\Service\ParseCss::parseScripts()

**Comment by degobbis** [comment]
I can't reproduce Your issue `0 - Call to undefined method Jtaldef\Service\ParseCss::parseScripts()` but I found another one.
In 2.0.0-rc1 You can't select a service in the plugin configuration, wich I fixed in 2.0.0-rc2.

Please update to 2.0.0-rc2 and enable the system debug for a more detailed output of the error, then post it here.
Also a link to the page could be helpful.

Thx for Your help to fixing this issues and patience.

**Comment by pklinke** [comment]
The errors are gone now but the Google font is not loaded locally, unfortunately I don't have awesomefont on this site.
Update must be done manually after removing the tc1.

The site is not public yet but i can give you URL and login as pm.

**Comment by degobbis** [comment]
There is a new problem, the server I was downloading the fonts is down since today.
You can connect with me over Ringcentral (Glip).
For how to do look here: https://www.joomla.de/community/glip
Find me as Guido De Gobbis

**Comment by degobbis** [comment]
Fixed with [version 2.0.0-rc4](https://github.com/joomtools/plg_system_jtaldef/releases).
Please test it, thx.

**Comment by degobbis** [comment]
Can you please test, if the latest [version 2.0.1](https://github.com/joomtools/plg_system_jtaldef/releases) solves your problem?
So we can close this issue :-)

**Comment by degobbis** [comment]
Closed on the assumption that the problem will continue to not appear.

**Comment by degobbis** [comment]
Please try to clear the index and save the plugin setting again.



15.09.2022 20:37:48 pklinke ***@***.***>:
